# Generated by Django 4.2.2 on 2023-06-15 12:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('climb_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 14, 12, 34, 33, 338710, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to=settings.AUTH_USER_MODEL),
        ),
    ]
