# Generated by Django 4.2.2 on 2023-06-15 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_auth', '0002_alter_certificate_expire_date_alter_certificate_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='certificate',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 14, 13, 29, 36, 409339, tzinfo=datetime.timezone.utc)),
        ),
    ]
