# Generated by Django 4.2.2 on 2023-06-16 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_auth', '0003_rename_certificate_certificate_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 15, 19, 57, 20, 702703, tzinfo=datetime.timezone.utc)),
        ),
    ]
