# Generated by Django 4.2.2 on 2023-06-09 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('climb_api', '0002_photo_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='insert_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
