# Generated by Django 4.2.2 on 2023-06-10 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climb_api', '0004_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='route_id',
            new_name='route',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='user_id',
            new_name='user',
        ),
    ]
