# Generated by Django 4.2.2 on 2023-06-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_api', '0005_rename_route_id_favorite_route_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='route',
            name='image',
            field=models.ImageField(default='', upload_to='route_images/'),
            preserve_default=False,
        ),
    ]
