# Generated by Django 4.2.2 on 2023-07-04 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_courses', '0002_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(verbose_name=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
        ),
    ]
