# Generated by Django 4.2.2 on 2023-07-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climb_courses', '0003_alter_course_price'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0.0)), name='price_range'),
        ),
    ]
